FROM python:3.10-slim

WORKDIR /app

COPY ./requirements.txt /app

RUN pip install -r requirements.txt

COPY . /app

RUN touch -c /app/database.db

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]